# Generated by Django 3.0.7 on 2020-06-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfblogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
    ]
