# Generated by Django 3.0.7 on 2020-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfblogin', '0003_auto_20200615_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='fbid',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
